version: '3.3'
services:
  coredns:
    image: coredns/coredns
    command: -conf /data/Corefile
    volumes:
    - ./data:/data:ro
  alpine314:
    build:
      context: .
      dockerfile: Dockerfile.alpine314
    dns:
    - ${COREDNS_IP}
  alpine318:
    build:
      context: .
      dockerfile: Dockerfile.alpine318
    dns:
    - ${COREDNS_IP}
  bullseye:
    build:
      context: .
      dockerfile: Dockerfile.bullseye
    dns:
    - ${COREDNS_IP}
